#!/usr/bin/php
<?php

$path = getenv('PHPMAILER_PATH');
$path = $path ? $path : '/var/log/mail';

// Read incomming email
$input = file_get_contents('php://stdin');

// Parse receivers
preg_match('|^To: (.*)|', $input, $matches);

// Create file
$receivers = $matches ? implode('-', (array)$matches) : time();
$filename = $path . '/' . sprintf('%s-%s-%s.eml', date('dmY'), $receivers, microtime());

// Place email to
file_put_contents($filename, $input);
